module.exports = { rewrites : [ 
{ source: "/en/projects", destination: "/project/23", locale: false },
{ source: "/en/projects/:slug", destination: "/project/show/:slug", locale: false },
{ source: "/en/projects/:slug/:sector", destination: "/project/sector/:slug~:sector", locale: false },
{ source: "/en/projects/:slug/:sector/:floor", destination: "/project/floor/:slug~:sector~:floor", locale: false },
{ source: "/en/projects/:slug/:sector/:floor/:flat", destination: "/project/flat/:slug~:sector~:floor~:flat", locale: false },
{ source: "/ka/projects", destination: "/project/23", locale: false },
{ source: "/ka/projects/:slug", destination: "/project/show/:slug", locale: false },
{ source: "/ka/projects/:slug/:sector", destination: "/project/sector/:slug~:sector", locale: false },
{ source: "/ka/projects/:slug/:sector/:floor", destination: "/project/floor/:slug~:sector~:floor", locale: false },
{ source: "/ka/projects/:slug/:sector/:floor/:flat", destination: "/project/flat/:slug~:sector~:floor~:flat", locale: false },
{ source: "/en/about-us-1", destination: "/text/30", locale: false },
{ source: "/ka/about-us-1", destination: "/text/30", locale: false },
{ source: "/en/construction-process", destination: "/timeline/25", locale: false },
{ source: "/ka/construction-process", destination: "/timeline/25", locale: false },
{ source: "/en/news", destination: "/nws/26", locale: false },
{ source: "/en/news/:slug", destination: "/nws/show/:slug", locale: false },
{ source: "/en/news/:page*", destination: "/nws", locale: false },
{ source: "/ka/news", destination: "/nws/26", locale: false },
{ source: "/ka/news/:slug", destination: "/nws/show/:slug", locale: false },
{ source: "/ka/news/:page*", destination: "/nws", locale: false },
{ source: "/en/faq", destination: "/fq/27", locale: false },
{ source: "/ka/faq", destination: "/fq/27", locale: false },
{ source: "/en/contact", destination: "/form/29", locale: false },
{ source: "/ka/contact", destination: "/form/29", locale: false },

] }